###

if [[ -z $MYS_DIR ]]; then
    echo "ERROR: MYS_DIR is not defined. Stop sourcing $0"
    return 0
fi

export fpath=($MYS_MODDIR/BASE/share/zsh/5.9/functions $fpath)

source $MYS_DIR/etc/omz/omz.sh
source $MYS_DIR/script/zsh-functions.sh

# Write to .zsh_history immediately
unsetopt INC_APPEND_HISTORY
unsetopt SHARE_HISTORY
setopt INC_APPEND_HISTORY_TIME

# Bash-like history up-down keys
# See https://unix.stackexchange.com/a/324658
bindkey "$terminfo[kcuu1]" up-history
bindkey "$terminfo[kcud1]" down-history
