name: Test Code in include/mys

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi', 'intelmpi' ]  # Test with MPICH, OpenMPI and IntelMPI
    name: Test with ${{ matrix.mpi }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MPI (${{ matrix.mpi }})
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Navigate to test directory and run make
        run: |
          cd test
          make

      # Optional: Run the tests if the Makefile generates executables
      # Replace 'test_executable' with the actual name of your test executable
      # - name: Run tests
      #  run: |
      #    cd test
      #    mpiexec -n 2 ./test_executable  # Adjust the executable name and number of processes

    runs-on: macos-latest
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi' ]  # Test with MPICH and OpenMPI
    name: Test with ${{ matrix.mpi }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MPI (${{ matrix.mpi }})
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Navigate to test directory and run make
        run: |
          cd test
          make
