name: Test Code in include/mys

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-linux-intel:
    name: Test with IntelMPI on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        oneapi-compiler: [2025.1]
        oneapi-mpi: [2021.16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Intel Apt repository
        timeout-minutes: 5
        run: |
          curl -sS -L https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/oneAPI.list" -o APT::Get::List-Cleanup="0"

      - name: Install Intel oneAPI compilers & MPI
        timeout-minutes: 5
        run: |
          sudo apt-get install --no-install-recommends intel-oneapi-compiler-dpcpp-cpp-${{ matrix.oneapi-compiler }}
          sudo apt-get install --no-install-recommends intel-oneapi-mpi-${{ matrix.oneapi-mpi }}
          ls /opt/intel/oneapi /opt/intel/oneapi/compiler /opt/intel/oneapi/mpi

      - name: Verify Intel oneAPI compilers & MPI
        run: |
          source /opt/intel/oneapi/setvars.sh
          echo $PATH
          echo $LD_LIBRARY_PATH
          which icc || echo "icc not found"
          which icpc || echo "icpc not found"
          which icx || echo "icx not found"
          which icpx || echo "icpx not found"
          which mpiicc || echo "mpiicc not found"
          which mpiicpc || echo "mpiicpc not found"
          icc --version || echo "FAILED: icc --version"
          icpc --version || echo "FAILED: icpc --version"
          icx --version || echo "FAILED: icx --version"
          icpx --version || echo "FAILED: icpx --version"
          mpiicc --version || echo "FAILED: mpiicc --version"
          mpiicpc --version || echo "FAILED: mpiicpc --version"

      - name: Build tests in test/ folder
        run: |
          source /opt/intel/oneapi/setvars.sh
          cd test
          make CC=icc CXX=icpc MPICC=mpiicc MPICXX=mpiicpc

      - name: Run tests in test/ folder
        run: |
          source /opt/intel/oneapi/setvars.sh
          cd test
          ./ex01.hello-gcc.exe
          ./ex02.hello-g++.exe
          mpirun -n 2 ./ex03.hello-mpicc.exe
          mpirun -n 2 ./ex04.hello-mpic++.exe
