name: Test Code in include/mys

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_linux:
    name: Test with ${{ matrix.mpi }} on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi', 'intelmpi' ]  # Test with MPICH, OpenMPI, and IntelMPI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MPI (${{ matrix.mpi }})
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Navigate to test directory and run make
        run: |
          cd test
          make

      # Optional: Run tests if Makefile generates executables
      # - name: Run tests
      #   run: |
      #     cd test
      #     mpiexec -n 2 ./test_executable

  test_macos:
    name: Test with ${{ matrix.mpi }} on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi' ]  # Test with MPICH and OpenMPI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MPI (${{ matrix.mpi }})
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Navigate to test directory and run make
        run: |
          cd test
          make
